import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is Next's own auto-generated file (regenerated by every
    // `next dev`/`next build` — as of Next 15 it also references
    // `.next/types/routes.d.ts` for typed routes), never hand-edited.
    ignores: [".next/**", "node_modules/**", "next-env.d.ts"],
  },
];

export default eslintConfig;
