"""add_death_saves_to_characters

Revision ID: 05e55ada520e
Revises: a2a1bf4460ff
Create Date: 2026-08-25 09:38:40.298384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e55ada520e'
down_revision: Union[str, Sequence[str], None] = 'a2a1bf4460ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'characters',
        sa.Column(
            'death_save_successes', sa.Integer(), nullable=False, server_default='0'
        ),
    )
    op.add_column(
        'characters',
        sa.Column(
            'death_save_failures', sa.Integer(), nullable=False, server_default='0'
        ),
    )
    op.add_column(
        'characters',
        sa.Column('is_dead', sa.Boolean(), nullable=False, server_default='false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'is_dead')
    op.drop_column('characters', 'death_save_failures')
    op.drop_column('characters', 'death_save_successes')
    # ### end Alembic commands ###
