"""add catalog i18n foundation and fixed vocabulary

Revision ID: 0ab8e6ca5757
Revises: 53987eab480a
Create Date: 2026-08-22 21:28:41.733926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ab8e6ca5757"
down_revision: Union[str, Sequence[str], None] = "53987eab480a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_ability_score_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_ability_score_definitions_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_ability_score_definitions_index"),
        "catalog_ability_score_definitions",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_alignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_alignments_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_alignments_index"),
        "catalog_alignments",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_conditions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_conditions_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_conditions_index"),
        "catalog_conditions",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_damage_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_damage_types_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_damage_types_index"),
        "catalog_damage_types",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_languages",
        sa.Column(
            "language_type",
            sa.Enum("standard", "exotic", name="languagetype"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_languages_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_languages_index"), "catalog_languages", ["index"], unique=False
    )
    op.create_table(
        "catalog_magic_schools",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_magic_schools_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_magic_schools_index"),
        "catalog_magic_schools",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_weapon_properties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_weapon_properties_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_weapon_properties_index"),
        "catalog_weapon_properties",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_ability_score_definitions_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_ability_score_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "locale", name="uq_catalog_ability_score_definitions_i18n"
        ),
    )
    op.create_table(
        "catalog_alignments_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("abbreviation", sa.String(length=5), nullable=False),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_alignments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_alignments_i18n"),
    )
    op.create_table(
        "catalog_conditions_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_conditions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_conditions_i18n"),
    )
    op.create_table(
        "catalog_damage_types_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_damage_types.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_damage_types_i18n"),
    )
    op.create_table(
        "catalog_languages_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("script", sa.String(length=100), nullable=True),
        sa.Column("typical_speakers", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_languages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_languages_i18n"),
    )
    op.create_table(
        "catalog_magic_schools_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("desc", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_magic_schools.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "locale", name="uq_catalog_magic_schools_i18n"
        ),
    )
    op.create_table(
        "catalog_skill_definitions",
        sa.Column("ability_score_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_skill_definitions_custom_campaign_scope",
        ),
        sa.ForeignKeyConstraint(
            ["ability_score_id"],
            ["catalog_ability_score_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_skill_definitions_index"),
        "catalog_skill_definitions",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_weapon_properties_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_weapon_properties.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "locale", name="uq_catalog_weapon_properties_i18n"
        ),
    )
    op.create_table(
        "catalog_skill_definitions_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_skill_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "locale", name="uq_catalog_skill_definitions_i18n"
        ),
    )
    op.create_check_constraint(
        "ck_catalog_class_definitions_custom_campaign_scope",
        "catalog_class_definitions",
        "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
    )
    op.create_check_constraint(
        "ck_catalog_races_custom_campaign_scope",
        "catalog_races",
        "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
    )
    op.create_check_constraint(
        "ck_catalog_subclass_definitions_custom_campaign_scope",
        "catalog_subclass_definitions",
        "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_catalog_subclass_definitions_custom_campaign_scope",
        "catalog_subclass_definitions",
        type_="check",
    )
    op.drop_constraint(
        "ck_catalog_races_custom_campaign_scope", "catalog_races", type_="check"
    )
    op.drop_constraint(
        "ck_catalog_class_definitions_custom_campaign_scope",
        "catalog_class_definitions",
        type_="check",
    )
    op.drop_table("catalog_skill_definitions_i18n")
    op.drop_table("catalog_weapon_properties_i18n")
    op.drop_index(
        op.f("ix_catalog_skill_definitions_index"),
        table_name="catalog_skill_definitions",
    )
    op.drop_table("catalog_skill_definitions")
    op.drop_table("catalog_magic_schools_i18n")
    op.drop_table("catalog_languages_i18n")
    op.drop_table("catalog_damage_types_i18n")
    op.drop_table("catalog_conditions_i18n")
    op.drop_table("catalog_alignments_i18n")
    op.drop_table("catalog_ability_score_definitions_i18n")
    op.drop_index(
        op.f("ix_catalog_weapon_properties_index"),
        table_name="catalog_weapon_properties",
    )
    op.drop_table("catalog_weapon_properties")
    op.drop_index(
        op.f("ix_catalog_magic_schools_index"), table_name="catalog_magic_schools"
    )
    op.drop_table("catalog_magic_schools")
    op.drop_index(op.f("ix_catalog_languages_index"), table_name="catalog_languages")
    op.drop_table("catalog_languages")
    sa.Enum(name="languagetype").drop(op.get_bind(), checkfirst=True)
    op.drop_index(
        op.f("ix_catalog_damage_types_index"), table_name="catalog_damage_types"
    )
    op.drop_table("catalog_damage_types")
    op.drop_index(op.f("ix_catalog_conditions_index"), table_name="catalog_conditions")
    op.drop_table("catalog_conditions")
    op.drop_index(op.f("ix_catalog_alignments_index"), table_name="catalog_alignments")
    op.drop_table("catalog_alignments")
    op.drop_index(
        op.f("ix_catalog_ability_score_definitions_index"),
        table_name="catalog_ability_score_definitions",
    )
    op.drop_table("catalog_ability_score_definitions")
    # ### end Alembic commands ###
