"""add world relation junction tables

Revision ID: 14ecbccdaf78
Revises: fbcce0468d89
Create Date: 2026-08-23 18:31:23.520784

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14ecbccdaf78"
down_revision: str | Sequence[str] | None = "fbcce0468d89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faction_relationships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("faction_a_id", sa.Uuid(), nullable=False),
        sa.Column("faction_b_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "allied",
                "hostile",
                "neutral",
                "vassal",
                "trade_partner",
                name="factionrelationshiptype",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["faction_a_id"], ["factions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["faction_b_id"], ["factions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "faction_a_id", "faction_b_id", name="uq_faction_relationships"
        ),
    )
    op.create_table(
        "location_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("visit_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location_id", "session_id", name="uq_location_sessions"),
    )
    op.create_table(
        "npc_factions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("npc_id", sa.Uuid(), nullable=False),
        sa.Column("faction_id", sa.Uuid(), nullable=False),
        sa.Column("role_in_faction", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["faction_id"], ["factions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["npc_id"], ["npcs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("npc_id", "faction_id", name="uq_npc_factions"),
    )
    op.create_table(
        "npc_locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("npc_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column(
            "presence_type",
            sa.Enum("resides", "frequents", "controls", name="npclocationpresencetype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["npc_id"], ["npcs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("npc_id", "location_id", name="uq_npc_locations"),
    )
    op.create_table(
        "npc_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("npc_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("appearance_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["npc_id"], ["npcs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("npc_id", "session_id", name="uq_npc_sessions"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("npc_sessions")
    op.drop_table("npc_locations")
    op.drop_table("npc_factions")
    op.drop_table("location_sessions")
    op.drop_table("faction_relationships")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS npclocationpresencetype")
    op.execute("DROP TYPE IF EXISTS factionrelationshiptype")
