"""add catalog proficiencies

Revision ID: 1b5ef8883035
Revises: 0ab8e6ca5757
Create Date: 2026-08-22 21:38:24.522633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b5ef8883035"
down_revision: Union[str, Sequence[str], None] = "0ab8e6ca5757"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_proficiencies",
        sa.Column(
            "proficiency_type",
            sa.Enum(
                "skill",
                "saving_throw",
                "weapon",
                "armor",
                "tool",
                "other",
                name="proficiencytype",
            ),
            nullable=False,
        ),
        sa.Column("skill_id", sa.UUID(), nullable=True),
        sa.Column("ability_score_id", sa.UUID(), nullable=True),
        sa.Column("equipment_category_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(proficiency_type = 'skill' AND skill_id IS NOT NULL   AND ability_score_id IS NULL AND equipment_category_id IS NULL) OR (proficiency_type = 'saving_throw' AND ability_score_id IS NOT NULL   AND skill_id IS NULL AND equipment_category_id IS NULL) OR (proficiency_type IN ('weapon', 'armor', 'tool')   AND equipment_category_id IS NOT NULL   AND skill_id IS NULL AND ability_score_id IS NULL) OR (proficiency_type = 'other' AND skill_id IS NULL   AND ability_score_id IS NULL AND equipment_category_id IS NULL)",
            name="ck_catalog_proficiencies_reference_scope",
        ),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_proficiencies_custom_campaign_scope",
        ),
        sa.ForeignKeyConstraint(
            ["ability_score_id"],
            ["catalog_ability_score_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["catalog_skill_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_proficiencies_index"),
        "catalog_proficiencies",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_proficiencies_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_proficiencies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "locale", name="uq_catalog_proficiencies_i18n"
        ),
    )
    op.create_table(
        "catalog_proficiency_classes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("proficiency_id", sa.UUID(), nullable=False),
        sa.Column("class_definition_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_definition_id"],
            ["catalog_class_definitions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["proficiency_id"], ["catalog_proficiencies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "proficiency_id",
            "class_definition_id",
            name="uq_catalog_proficiency_classes",
        ),
    )
    op.create_table(
        "catalog_proficiency_races",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("proficiency_id", sa.UUID(), nullable=False),
        sa.Column("race_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proficiency_id"], ["catalog_proficiencies.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["race_id"], ["catalog_races.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "proficiency_id", "race_id", name="uq_catalog_proficiency_races"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("catalog_proficiency_races")
    op.drop_table("catalog_proficiency_classes")
    op.drop_table("catalog_proficiencies_i18n")
    op.drop_index(
        op.f("ix_catalog_proficiencies_index"), table_name="catalog_proficiencies"
    )
    op.drop_table("catalog_proficiencies")
    sa.Enum(name="proficiencytype").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
