"""expand catalog races with i18n, index, and full traits

Revision ID: 4a3a38b85c46
Revises: 1b5ef8883035
Create Date: 2026-08-22 21:45:18.693692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a3a38b85c46"
down_revision: Union[str, Sequence[str], None] = "1b5ef8883035"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_races_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("age", sa.Text(), nullable=False),
        sa.Column("alignment_desc", sa.Text(), nullable=False),
        sa.Column("size_description", sa.Text(), nullable=False),
        sa.Column("language_desc", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_races.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_races_i18n"),
    )
    op.create_table(
        "catalog_race_traits_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("trait_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_race_traits.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_race_traits_i18n"),
    )
    op.create_table(
        "catalog_subraces_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_subraces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_subraces_i18n"),
    )
    op.create_table(
        "catalog_subrace_traits_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("trait_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_subrace_traits.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "locale", name="uq_catalog_subrace_traits_i18n"
        ),
    )
    op.drop_column("catalog_race_traits", "description")
    op.drop_column("catalog_race_traits", "trait_name")
    op.add_column(
        "catalog_races", sa.Column("index", sa.String(length=100), nullable=True)
    )
    op.drop_index(op.f("ix_catalog_races_name"), table_name="catalog_races")
    op.create_index(
        op.f("ix_catalog_races_index"), "catalog_races", ["index"], unique=False
    )
    op.drop_column("catalog_races", "description")
    op.drop_column("catalog_races", "name")
    op.drop_column("catalog_subrace_traits", "description")
    op.drop_column("catalog_subrace_traits", "trait_name")
    op.add_column(
        "catalog_subraces", sa.Column("index", sa.String(length=100), nullable=True)
    )
    op.create_index(
        op.f("ix_catalog_subraces_index"), "catalog_subraces", ["index"], unique=False
    )
    op.drop_column("catalog_subraces", "description")
    op.drop_column("catalog_subraces", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "catalog_subraces",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.add_column(
        "catalog_subraces",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_catalog_subraces_index"), table_name="catalog_subraces")
    op.drop_column("catalog_subraces", "index")
    op.add_column(
        "catalog_subrace_traits",
        sa.Column(
            "trait_name", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "catalog_subrace_traits",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "catalog_races",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.add_column(
        "catalog_races",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_catalog_races_index"), table_name="catalog_races")
    op.create_index(
        op.f("ix_catalog_races_name"), "catalog_races", ["name"], unique=False
    )
    op.drop_column("catalog_races", "index")
    op.add_column(
        "catalog_race_traits",
        sa.Column(
            "trait_name", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "catalog_race_traits",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_table("catalog_subrace_traits_i18n")
    op.drop_table("catalog_subraces_i18n")
    op.drop_table("catalog_race_traits_i18n")
    op.drop_table("catalog_races_i18n")
    # ### end Alembic commands ###
