"""add catalog tables

Revision ID: 53987eab480a
Revises: 6824fb4d9270
Create Date: 2026-04-21 16:59:53.231585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53987eab480a'
down_revision: Union[str, Sequence[str], None] = '6824fb4d9270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_class_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hit_die', sa.Integer(), nullable=False),
    sa.Column('primary_ability', sa.String(length=100), nullable=False),
    sa.Column('saving_throw_proficiencies', sa.String(length=100), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_class_definitions_name'), 'catalog_class_definitions', ['name'], unique=False)
    op.create_table('catalog_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('properties', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_items_name'), 'catalog_items', ['name'], unique=False)
    op.create_table('catalog_races',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('darkvision_range', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_races_name'), 'catalog_races', ['name'], unique=False)
    op.create_table('catalog_spells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=50), nullable=False),
    sa.Column('casting_time', sa.String(length=100), nullable=False),
    sa.Column('range', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('components', sa.String(length=100), nullable=False),
    sa.Column('ritual', sa.Boolean(), nullable=False),
    sa.Column('concentration', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('higher_levels', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_spells_name'), 'catalog_spells', ['name'], unique=False)
    op.create_table('catalog_armor_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('base_ac', sa.Integer(), nullable=False),
    sa.Column('dex_bonus_cap', sa.Integer(), nullable=True),
    sa.Column('stealth_disadvantage', sa.Boolean(), nullable=False),
    sa.Column('strength_requirement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('catalog_class_level_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_definition_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mechanical_effect', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['class_definition_id'], ['catalog_class_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_race_traits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('trait_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mechanical_effect', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['catalog_races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_subclass_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_definition_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['class_definition_id'], ['catalog_class_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_subraces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['catalog_races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_weapon_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('damage_dice', sa.String(length=20), nullable=False),
    sa.Column('damage_type', sa.String(length=30), nullable=False),
    sa.Column('weapon_range', sa.String(length=50), nullable=False),
    sa.Column('weapon_properties', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('catalog_race_ability_bonuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=True),
    sa.Column('subrace_id', sa.UUID(), nullable=True),
    sa.Column('ability', sa.String(length=3), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['catalog_races.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subrace_id'], ['catalog_subraces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_subrace_traits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subrace_id', sa.UUID(), nullable=False),
    sa.Column('trait_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mechanical_effect', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['subrace_id'], ['catalog_subraces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_subrace_traits')
    op.drop_table('catalog_race_ability_bonuses')
    op.drop_table('catalog_weapon_details')
    op.drop_table('catalog_subraces')
    op.drop_table('catalog_subclass_definitions')
    op.drop_table('catalog_race_traits')
    op.drop_table('catalog_class_level_features')
    op.drop_table('catalog_armor_details')
    op.drop_index(op.f('ix_catalog_spells_name'), table_name='catalog_spells')
    op.drop_table('catalog_spells')
    op.drop_index(op.f('ix_catalog_races_name'), table_name='catalog_races')
    op.drop_table('catalog_races')
    op.drop_index(op.f('ix_catalog_items_name'), table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_index(op.f('ix_catalog_class_definitions_name'), table_name='catalog_class_definitions')
    op.drop_table('catalog_class_definitions')
    # ### end Alembic commands ###
