"""widen character feature choice uniqueness

Revision ID: 54374794b595
Revises: 172d0a9e7613
Create Date: 2026-08-25 21:19:03.542057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54374794b595'
down_revision: Union[str, Sequence[str], None] = '172d0a9e7613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_character_feature_choices'), 'character_feature_choices', type_='unique')
    op.create_unique_constraint('uq_character_feature_choices', 'character_feature_choices', ['character_id', 'feature_id', 'feature_option_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_character_feature_choices', 'character_feature_choices', type_='unique')
    op.create_unique_constraint(op.f('uq_character_feature_choices'), 'character_feature_choices', ['character_id', 'feature_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
