"""expand catalog classes with progression and features

Revision ID: 550deb637bf1
Revises: 4a3a38b85c46
Create Date: 2026-08-22 22:23:38.100333

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "550deb637bf1"
down_revision: str | Sequence[str] | None = "4a3a38b85c46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # The old `catalog_class_level_features` rows (denormalized feature_name/
    # description/level/class_definition_id) predate the `Feature`/`ClassLevel`
    # split below and can't be backfilled into the new junction shape — same
    # as the races migration, the seed re-populates everything from scratch,
    # so old rows referencing the tables this migration alters are cleared
    # first (cascades from `catalog_class_definitions` clear subclasses too).
    op.execute("DELETE FROM catalog_class_definitions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_class_definitions_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_class_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "locale", name="uq_catalog_class_definitions_i18n"
        ),
    )
    op.create_table(
        "catalog_class_levels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("class_definition_id", sa.UUID(), nullable=False),
        sa.Column("subclass_definition_id", sa.UUID(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("proficiency_bonus", sa.Integer(), nullable=True),
        sa.Column("ability_score_bonuses", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_definition_id"],
            ["catalog_class_definitions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subclass_definition_id"],
            ["catalog_subclass_definitions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "class_definition_id",
            "subclass_definition_id",
            "level",
            name="uq_catalog_class_levels",
        ),
    )
    op.create_table(
        "catalog_features",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("class_definition_id", sa.UUID(), nullable=True),
        sa.Column("subclass_definition_id", sa.UUID(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("parent_feature_id", sa.UUID(), nullable=True),
        sa.Column("mechanical_effect", sa.String(length=500), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_features_custom_campaign_scope",
        ),
        sa.CheckConstraint(
            "(class_definition_id IS NOT NULL AND subclass_definition_id IS NULL) OR (class_definition_id IS NULL AND subclass_definition_id IS NOT NULL)",
            name="ck_catalog_features_owner_scope",
        ),
        sa.ForeignKeyConstraint(
            ["class_definition_id"],
            ["catalog_class_definitions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_feature_id"], ["catalog_features.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["subclass_definition_id"],
            ["catalog_subclass_definitions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_features_index"), "catalog_features", ["index"], unique=False
    )
    op.create_table(
        "catalog_subclass_definitions_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("flavor", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_subclass_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "locale", name="uq_catalog_subclass_definitions_i18n"
        ),
    )
    op.create_table(
        "catalog_class_level_resources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("class_level_id", sa.UUID(), nullable=False),
        sa.Column("resource_key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_level_id"], ["catalog_class_levels.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_class_level_spell_slots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("class_level_id", sa.UUID(), nullable=False),
        sa.Column("spell_level", sa.Integer(), nullable=False),
        sa.Column("slot_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_level_id"], ["catalog_class_levels.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_feature_prerequisites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.Column(
            "prerequisite_type",
            sa.Enum("level", "feature", "spell", name="featureprerequisitetype"),
            nullable=False,
        ),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("required_feature_id", sa.UUID(), nullable=True),
        sa.Column("spell_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["feature_id"], ["catalog_features.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["required_feature_id"], ["catalog_features.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["spell_id"], ["catalog_spells.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_features_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("feature_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_features.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_features_i18n"),
    )
    op.add_column(
        "catalog_class_definitions",
        sa.Column("index", sa.String(length=100), nullable=True),
    )
    op.drop_index(
        op.f("ix_catalog_class_definitions_name"),
        table_name="catalog_class_definitions",
    )
    op.create_index(
        op.f("ix_catalog_class_definitions_index"),
        "catalog_class_definitions",
        ["index"],
        unique=False,
    )
    op.drop_column("catalog_class_definitions", "name")
    op.add_column(
        "catalog_class_level_features",
        sa.Column("class_level_id", sa.UUID(), nullable=False),
    )
    op.add_column(
        "catalog_class_level_features",
        sa.Column("feature_id", sa.UUID(), nullable=False),
    )
    op.create_unique_constraint(
        "uq_catalog_class_level_features",
        "catalog_class_level_features",
        ["class_level_id", "feature_id"],
    )
    op.drop_constraint(
        op.f("catalog_class_level_features_class_definition_id_fkey"),
        "catalog_class_level_features",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "catalog_class_level_features_class_level_id_fkey",
        "catalog_class_level_features",
        "catalog_class_levels",
        ["class_level_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "catalog_class_level_features_feature_id_fkey",
        "catalog_class_level_features",
        "catalog_features",
        ["feature_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("catalog_class_level_features", "description")
    op.drop_column("catalog_class_level_features", "class_definition_id")
    op.drop_column("catalog_class_level_features", "level")
    op.drop_column("catalog_class_level_features", "feature_name")
    op.drop_column("catalog_class_level_features", "mechanical_effect")
    op.add_column(
        "catalog_subclass_definitions",
        sa.Column("index", sa.String(length=100), nullable=True),
    )
    op.create_index(
        op.f("ix_catalog_subclass_definitions_index"),
        "catalog_subclass_definitions",
        ["index"],
        unique=False,
    )
    op.drop_column("catalog_subclass_definitions", "description")
    op.drop_column("catalog_subclass_definitions", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "catalog_subclass_definitions",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.add_column(
        "catalog_subclass_definitions",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_index(
        op.f("ix_catalog_subclass_definitions_index"),
        table_name="catalog_subclass_definitions",
    )
    op.drop_column("catalog_subclass_definitions", "index")
    op.add_column(
        "catalog_class_level_features",
        sa.Column(
            "mechanical_effect",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "catalog_class_level_features",
        sa.Column(
            "feature_name", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "catalog_class_level_features",
        sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "catalog_class_level_features",
        sa.Column(
            "class_definition_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "catalog_class_level_features",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        "catalog_class_level_features_class_level_id_fkey",
        "catalog_class_level_features",
        type_="foreignkey",
    )
    op.drop_constraint(
        "catalog_class_level_features_feature_id_fkey",
        "catalog_class_level_features",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("catalog_class_level_features_class_definition_id_fkey"),
        "catalog_class_level_features",
        "catalog_class_definitions",
        ["class_definition_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "uq_catalog_class_level_features",
        "catalog_class_level_features",
        type_="unique",
    )
    op.drop_column("catalog_class_level_features", "feature_id")
    op.drop_column("catalog_class_level_features", "class_level_id")
    op.add_column(
        "catalog_class_definitions",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.drop_index(
        op.f("ix_catalog_class_definitions_index"),
        table_name="catalog_class_definitions",
    )
    op.create_index(
        op.f("ix_catalog_class_definitions_name"),
        "catalog_class_definitions",
        ["name"],
        unique=False,
    )
    op.drop_column("catalog_class_definitions", "index")
    op.drop_table("catalog_features_i18n")
    op.drop_table("catalog_feature_prerequisites")
    op.drop_table("catalog_class_level_spell_slots")
    op.drop_table("catalog_class_level_resources")
    op.drop_table("catalog_subclass_definitions_i18n")
    op.drop_index(op.f("ix_catalog_features_index"), table_name="catalog_features")
    op.drop_table("catalog_features")
    op.drop_table("catalog_class_levels")
    op.drop_table("catalog_class_definitions_i18n")
    # ### end Alembic commands ###
    sa.Enum(name="featureprerequisitetype").drop(op.get_bind(), checkfirst=True)
