"""add catalog rules and rule sections

Revision ID: 6f9cf284365a
Revises: f75f2c608e22
Create Date: 2026-08-23 00:35:18.249872

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f9cf284365a"
down_revision: Union[str, Sequence[str], None] = "f75f2c608e22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_rule_sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_rule_sections_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_rule_sections_index"),
        "catalog_rule_sections",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_rules_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_rules_index"), "catalog_rules", ["index"], unique=False
    )
    op.create_table(
        "catalog_rule_rule_sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("rule_section_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["rule_id"], ["catalog_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["rule_section_id"], ["catalog_rule_sections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "rule_id", "rule_section_id", name="uq_catalog_rule_rule_sections"
        ),
    )
    op.create_table(
        "catalog_rule_sections_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_rule_sections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "locale", name="uq_catalog_rule_sections_i18n"
        ),
    )
    op.create_table(
        "catalog_rules_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_rules.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_rules_i18n"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("catalog_rules_i18n")
    op.drop_table("catalog_rule_sections_i18n")
    op.drop_table("catalog_rule_rule_sections")
    op.drop_index(op.f("ix_catalog_rules_index"), table_name="catalog_rules")
    op.drop_table("catalog_rules")
    op.drop_index(
        op.f("ix_catalog_rule_sections_index"), table_name="catalog_rule_sections"
    )
    op.drop_table("catalog_rule_sections")
    # ### end Alembic commands ###
