"""add generation_method to characters

Revision ID: 734593cbe472
Revises: 7c1e88f5c532
Create Date: 2026-08-25 16:32:26.431763

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '734593cbe472'
down_revision: str | Sequence[str] | None = '7c1e88f5c532'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    generation_method_enum = sa.Enum(
        "standard_array", "point_buy", "custom", "roll", name="abilitygenerationmethod"
    )
    generation_method_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "characters",
        sa.Column(
            "generation_method",
            generation_method_enum,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'generation_method')
    # ### end Alembic commands ###
    sa.Enum(name="abilitygenerationmethod").drop(op.get_bind(), checkfirst=True)
