"""add_character_resources

Revision ID: 7d0caa036dd1
Revises: 62a1ec4d1e1f
Create Date: 2026-08-25 10:04:58.801438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0caa036dd1'
down_revision: Union[str, Sequence[str], None] = '62a1ec4d1e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('resource_key', sa.String(length=100), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'resource_key', name='uq_character_resources')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_resources')
    # ### end Alembic commands ###
