"""add last feature option to character resources

Revision ID: 81685be0972e
Revises: 9c57951e4613
Create Date: 2026-08-25 18:15:45.840714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81685be0972e'
down_revision: Union[str, Sequence[str], None] = '9c57951e4613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_resources', sa.Column('last_feature_option_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'character_resources', 'catalog_features', ['last_feature_option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character_resources', type_='foreignkey')
    op.drop_column('character_resources', 'last_feature_option_id')
    # ### end Alembic commands ###
