"""add character feature choices

Revision ID: 9c57951e4613
Revises: 734593cbe472
Create Date: 2026-08-25 16:56:31.596144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c57951e4613'
down_revision: Union[str, Sequence[str], None] = '734593cbe472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_feature_choices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('feature_option_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['catalog_features.id'], ),
    sa.ForeignKeyConstraint(['feature_option_id'], ['catalog_features.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'feature_id', name='uq_character_feature_choices')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_feature_choices')
    # ### end Alembic commands ###
