"""add hit_dice_used to character_classes

Revision ID: a2a1bf4460ff
Revises: bfd9155ca261
Create Date: 2026-08-25 09:29:23.310172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a1bf4460ff'
down_revision: Union[str, Sequence[str], None] = 'bfd9155ca261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'character_classes',
        sa.Column('hit_dice_used', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_classes', 'hit_dice_used')
    # ### end Alembic commands ###
