"""add catalog magic items

Revision ID: b8f90e4b9664
Revises: e6a9cb74db4e
Create Date: 2026-08-22 22:49:28.886482

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8f90e4b9664"
down_revision: str | Sequence[str] | None = "e6a9cb74db4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_magic_items",
        sa.Column("equipment_category_id", sa.UUID(), nullable=False),
        sa.Column("rarity", sa.String(length=20), nullable=False),
        sa.Column("is_variant", sa.Boolean(), nullable=False),
        sa.Column("variant_of_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_magic_items_custom_campaign_scope",
        ),
        sa.ForeignKeyConstraint(
            ["equipment_category_id"],
            ["catalog_equipment_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_of_id"], ["catalog_magic_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_magic_items_index"),
        "catalog_magic_items",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_magic_items_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_magic_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_magic_items_i18n"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("catalog_magic_items_i18n")
    op.drop_index(
        op.f("ix_catalog_magic_items_index"), table_name="catalog_magic_items"
    )
    op.drop_table("catalog_magic_items")
    # ### end Alembic commands ###
