"""expand catalog spells with i18n, classes and magic school fk

Revision ID: d95c9bd92d79
Revises: 550deb637bf1
Create Date: 2026-08-22 22:36:24.812350

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d95c9bd92d79"
down_revision: str | Sequence[str] | None = "550deb637bf1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # The old `catalog_spells` rows (denormalized `school`/`name`/`description`
    # strings) predate `magic_school_id`/`SpellI18n` below and can't be
    # backfilled — same as the classes migration, the seed re-populates
    # everything from scratch, so old rows are cleared before the new NOT
    # NULL `magic_school_id` column is added.
    op.execute("DELETE FROM catalog_spells")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_spell_classes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("spell_id", sa.UUID(), nullable=False),
        sa.Column("class_definition_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_definition_id"],
            ["catalog_class_definitions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["spell_id"], ["catalog_spells.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "spell_id", "class_definition_id", name="uq_catalog_spell_classes"
        ),
    )
    op.create_table(
        "catalog_spells_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("higher_levels", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_spells.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_spells_i18n"),
    )
    op.add_column(
        "catalog_spells", sa.Column("index", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "catalog_spells", sa.Column("magic_school_id", sa.UUID(), nullable=False)
    )
    op.add_column(
        "catalog_spells", sa.Column("is_custom", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "catalog_spells", sa.Column("created_by_id", sa.UUID(), nullable=True)
    )
    op.add_column("catalog_spells", sa.Column("campaign_id", sa.UUID(), nullable=True))
    op.drop_index(op.f("ix_catalog_spells_name"), table_name="catalog_spells")
    op.create_index(
        op.f("ix_catalog_spells_index"), "catalog_spells", ["index"], unique=False
    )
    op.create_foreign_key(
        "catalog_spells_magic_school_id_fkey",
        "catalog_spells",
        "catalog_magic_schools",
        ["magic_school_id"],
        ["id"],
    )
    op.create_check_constraint(
        "ck_catalog_spells_custom_campaign_scope",
        "catalog_spells",
        "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
    )
    op.drop_column("catalog_spells", "description")
    op.drop_column("catalog_spells", "name")
    op.drop_column("catalog_spells", "school")
    op.drop_column("catalog_spells", "higher_levels")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "catalog_spells",
        sa.Column("higher_levels", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "catalog_spells",
        sa.Column("school", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.add_column(
        "catalog_spells",
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.add_column(
        "catalog_spells",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        "ck_catalog_spells_custom_campaign_scope", "catalog_spells", type_="check"
    )
    op.drop_constraint(
        "catalog_spells_magic_school_id_fkey", "catalog_spells", type_="foreignkey"
    )
    op.drop_index(op.f("ix_catalog_spells_index"), table_name="catalog_spells")
    op.create_index(
        op.f("ix_catalog_spells_name"), "catalog_spells", ["name"], unique=False
    )
    op.drop_column("catalog_spells", "campaign_id")
    op.drop_column("catalog_spells", "created_by_id")
    op.drop_column("catalog_spells", "is_custom")
    op.drop_column("catalog_spells", "magic_school_id")
    op.drop_column("catalog_spells", "index")
    op.drop_table("catalog_spells_i18n")
    op.drop_table("catalog_spell_classes")
    # ### end Alembic commands ###
