"""expand catalog items with i18n, equipment categories and properties

Revision ID: e6a9cb74db4e
Revises: d95c9bd92d79
Create Date: 2026-08-22 22:44:07.678984

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6a9cb74db4e"
down_revision: str | Sequence[str] | None = "d95c9bd92d79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # The old `catalog_items`/`catalog_weapon_details` rows (denormalized
    # `name`/`description`/`properties`/`damage_type` strings, and an
    # `item_type` value — `magic_item` — that no longer exists in the new
    # enum) predate `ItemI18n`/`equipment_category_id`/`damage_type_id` below
    # and can't be backfilled — same as the classes/spells migrations, the
    # seed re-populates everything from scratch, so old rows are cleared
    # first (cascades clear their weapon/armor details too).
    op.execute("DELETE FROM catalog_items")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_equipment_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_equipment_categories_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_equipment_categories_index"),
        "catalog_equipment_categories",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_equipment_categories_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_equipment_categories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "locale", name="uq_catalog_equipment_categories_i18n"
        ),
    )
    op.create_table(
        "catalog_item_properties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("weapon_property_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["catalog_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["weapon_property_id"], ["catalog_weapon_properties.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "item_id", "weapon_property_id", name="uq_catalog_item_properties"
        ),
    )
    op.create_table(
        "catalog_items_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_items_i18n"),
    )
    op.add_column(
        "catalog_items", sa.Column("index", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "catalog_items", sa.Column("equipment_category_id", sa.UUID(), nullable=False)
    )
    op.add_column("catalog_items", sa.Column("is_custom", sa.Boolean(), nullable=False))
    op.add_column("catalog_items", sa.Column("created_by_id", sa.UUID(), nullable=True))
    op.add_column("catalog_items", sa.Column("campaign_id", sa.UUID(), nullable=True))
    # `alter_column` to an Enum type doesn't issue `CREATE TYPE` itself (unlike
    # a brand-new Enum column, which creates it implicitly) — create it first.
    sa.Enum("weapon", "armor", "gear", "tool", "consumable", name="itemtype").create(
        op.get_bind(), checkfirst=True
    )
    op.alter_column(
        "catalog_items",
        "item_type",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("weapon", "armor", "gear", "tool", "consumable", name="itemtype"),
        existing_nullable=False,
        postgresql_using="item_type::itemtype",
    )
    op.drop_index(op.f("ix_catalog_items_name"), table_name="catalog_items")
    op.create_index(
        op.f("ix_catalog_items_index"), "catalog_items", ["index"], unique=False
    )
    op.create_foreign_key(
        "catalog_items_equipment_category_id_fkey",
        "catalog_items",
        "catalog_equipment_categories",
        ["equipment_category_id"],
        ["id"],
    )
    op.create_check_constraint(
        "ck_catalog_items_custom_campaign_scope",
        "catalog_items",
        "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
    )
    op.drop_column("catalog_items", "properties")
    op.drop_column("catalog_items", "description")
    op.drop_column("catalog_items", "name")
    op.create_foreign_key(
        "catalog_proficiencies_equipment_category_id_fkey",
        "catalog_proficiencies",
        "catalog_equipment_categories",
        ["equipment_category_id"],
        ["id"],
    )
    op.add_column(
        "catalog_weapon_details", sa.Column("damage_type_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        "catalog_weapon_details_damage_type_id_fkey",
        "catalog_weapon_details",
        "catalog_damage_types",
        ["damage_type_id"],
        ["id"],
    )
    op.drop_column("catalog_weapon_details", "damage_type")
    op.drop_column("catalog_weapon_details", "weapon_properties")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "catalog_weapon_details",
        sa.Column(
            "weapon_properties",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "catalog_weapon_details",
        sa.Column(
            "damage_type", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        "catalog_weapon_details_damage_type_id_fkey",
        "catalog_weapon_details",
        type_="foreignkey",
    )
    op.drop_column("catalog_weapon_details", "damage_type_id")
    op.drop_constraint(
        "catalog_proficiencies_equipment_category_id_fkey",
        "catalog_proficiencies",
        type_="foreignkey",
    )
    op.add_column(
        "catalog_items",
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.add_column(
        "catalog_items",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "catalog_items",
        sa.Column(
            "properties", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        "ck_catalog_items_custom_campaign_scope", "catalog_items", type_="check"
    )
    op.drop_constraint(
        "catalog_items_equipment_category_id_fkey", "catalog_items", type_="foreignkey"
    )
    op.drop_index(op.f("ix_catalog_items_index"), table_name="catalog_items")
    op.create_index(
        op.f("ix_catalog_items_name"), "catalog_items", ["name"], unique=False
    )
    op.alter_column(
        "catalog_items",
        "item_type",
        existing_type=sa.Enum(
            "weapon", "armor", "gear", "tool", "consumable", name="itemtype"
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("catalog_items", "campaign_id")
    op.drop_column("catalog_items", "created_by_id")
    op.drop_column("catalog_items", "is_custom")
    op.drop_column("catalog_items", "equipment_category_id")
    op.drop_column("catalog_items", "index")
    op.drop_table("catalog_items_i18n")
    op.drop_table("catalog_item_properties")
    op.drop_table("catalog_equipment_categories_i18n")
    op.drop_index(
        op.f("ix_catalog_equipment_categories_index"),
        table_name="catalog_equipment_categories",
    )
    op.drop_table("catalog_equipment_categories")
    # ### end Alembic commands ###
    sa.Enum(name="itemtype").drop(op.get_bind(), checkfirst=True)
