"""add catalog backgrounds and feats

Revision ID: e931ad0dbbbc
Revises: b8f90e4b9664
Create Date: 2026-08-23 00:18:55.771705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e931ad0dbbbc"
down_revision: Union[str, Sequence[str], None] = "b8f90e4b9664"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_backgrounds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_backgrounds_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_backgrounds_index"),
        "catalog_backgrounds",
        ["index"],
        unique=False,
    )
    op.create_table(
        "catalog_feats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_feats_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_feats_index"), "catalog_feats", ["index"], unique=False
    )
    op.create_table(
        "catalog_background_features",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("background_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["background_id"], ["catalog_backgrounds.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("background_id"),
    )
    op.create_table(
        "catalog_backgrounds_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("personality_traits", sa.Text(), nullable=False),
        sa.Column("ideals", sa.Text(), nullable=False),
        sa.Column("bonds", sa.Text(), nullable=False),
        sa.Column("flaws", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_backgrounds.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_backgrounds_i18n"),
    )
    op.create_table(
        "catalog_feat_prerequisites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("feat_id", sa.UUID(), nullable=False),
        sa.Column("ability_score_id", sa.UUID(), nullable=True),
        sa.Column("minimum_score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ability_score_id"],
            ["catalog_ability_score_definitions.id"],
        ),
        sa.ForeignKeyConstraint(["feat_id"], ["catalog_feats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_feats_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_feats.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_feats_i18n"),
    )
    op.create_table(
        "catalog_background_equipment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("background_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["background_id"], ["catalog_backgrounds.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["item_id"], ["catalog_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_background_features_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("feature_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_background_features.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_id", "locale", name="uq_catalog_background_features_i18n"
        ),
    )
    op.create_table(
        "catalog_background_proficiencies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("background_id", sa.UUID(), nullable=False),
        sa.Column("proficiency_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["background_id"], ["catalog_backgrounds.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["proficiency_id"], ["catalog_proficiencies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "background_id",
            "proficiency_id",
            name="uq_catalog_background_proficiencies",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("catalog_background_proficiencies")
    op.drop_table("catalog_background_features_i18n")
    op.drop_table("catalog_background_equipment")
    op.drop_table("catalog_feats_i18n")
    op.drop_table("catalog_feat_prerequisites")
    op.drop_table("catalog_backgrounds_i18n")
    op.drop_table("catalog_background_features")
    op.drop_index(op.f("ix_catalog_feats_index"), table_name="catalog_feats")
    op.drop_table("catalog_feats")
    op.drop_index(
        op.f("ix_catalog_backgrounds_index"), table_name="catalog_backgrounds"
    )
    op.drop_table("catalog_backgrounds")
    # ### end Alembic commands ###
