"""add catalog monster stat blocks

Revision ID: f75f2c608e22
Revises: e931ad0dbbbc
Create Date: 2026-08-23 00:28:20.722048

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f75f2c608e22"
down_revision: str | Sequence[str] | None = "e931ad0dbbbc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_monsters",
        sa.Column(
            "size",
            sa.Enum(
                "tiny",
                "small",
                "medium",
                "large",
                "huge",
                "gargantuan",
                name="creaturesize",
            ),
            nullable=False,
        ),
        sa.Column("creature_type", sa.String(length=100), nullable=False),
        sa.Column("creature_subtype", sa.String(length=100), nullable=True),
        sa.Column("alignment", sa.String(length=100), nullable=False),
        sa.Column("hit_points", sa.Integer(), nullable=False),
        sa.Column("hit_dice", sa.String(length=50), nullable=False),
        sa.Column("challenge_rating", sa.Float(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("proficiency_bonus", sa.Integer(), nullable=True),
        sa.Column("languages", sa.String(length=300), nullable=False),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("dexterity", sa.Integer(), nullable=False),
        sa.Column("constitution", sa.Integer(), nullable=False),
        sa.Column("intelligence", sa.Integer(), nullable=False),
        sa.Column("wisdom", sa.Integer(), nullable=False),
        sa.Column("charisma", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=100), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(NOT is_custom AND campaign_id IS NULL) OR (is_custom AND campaign_id IS NOT NULL)",
            name="ck_catalog_monsters_custom_campaign_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_monsters_index"), "catalog_monsters", ["index"], unique=False
    )
    op.create_table(
        "catalog_monster_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monster_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("attack_bonus", sa.Integer(), nullable=True),
        sa.Column("save_ability_score_id", sa.UUID(), nullable=True),
        sa.Column("save_dc", sa.Integer(), nullable=True),
        sa.Column("usage_type", sa.String(length=50), nullable=True),
        sa.Column("usage_times", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["monster_id"], ["catalog_monsters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["save_ability_score_id"],
            ["catalog_ability_score_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_monster_armor_classes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monster_id", sa.UUID(), nullable=False),
        sa.Column("ac_type", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("condition_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["condition_id"],
            ["catalog_conditions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monster_id"], ["catalog_monsters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_monster_condition_immunities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monster_id", sa.UUID(), nullable=False),
        sa.Column("condition_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["condition_id"], ["catalog_conditions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["monster_id"], ["catalog_monsters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "monster_id", "condition_id", name="uq_catalog_monster_condition_immunities"
        ),
    )
    op.create_table(
        "catalog_monster_damage_modifiers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monster_id", sa.UUID(), nullable=False),
        sa.Column("damage_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "modifier_type",
            sa.Enum("vulnerable", "resistant", "immune", name="damagemodifiertype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["damage_type_id"],
            ["catalog_damage_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monster_id"], ["catalog_monsters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_monster_legendary_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monster_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("attack_bonus", sa.Integer(), nullable=True),
        sa.Column("save_ability_score_id", sa.UUID(), nullable=True),
        sa.Column("save_dc", sa.Integer(), nullable=True),
        sa.Column("usage_type", sa.String(length=50), nullable=True),
        sa.Column("usage_times", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["monster_id"], ["catalog_monsters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["save_ability_score_id"],
            ["catalog_ability_score_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_monster_reactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monster_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("attack_bonus", sa.Integer(), nullable=True),
        sa.Column("save_ability_score_id", sa.UUID(), nullable=True),
        sa.Column("save_dc", sa.Integer(), nullable=True),
        sa.Column("usage_type", sa.String(length=50), nullable=True),
        sa.Column("usage_times", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["monster_id"], ["catalog_monsters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["save_ability_score_id"],
            ["catalog_ability_score_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_monster_senses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monster_id", sa.UUID(), nullable=False),
        sa.Column("passive_perception", sa.Integer(), nullable=False),
        sa.Column("blindsight", sa.String(length=50), nullable=True),
        sa.Column("darkvision", sa.String(length=50), nullable=True),
        sa.Column("tremorsense", sa.String(length=50), nullable=True),
        sa.Column("truesight", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["monster_id"], ["catalog_monsters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("monster_id"),
    )
    op.create_table(
        "catalog_monster_special_abilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monster_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("attack_bonus", sa.Integer(), nullable=True),
        sa.Column("save_ability_score_id", sa.UUID(), nullable=True),
        sa.Column("save_dc", sa.Integer(), nullable=True),
        sa.Column("usage_type", sa.String(length=50), nullable=True),
        sa.Column("usage_times", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["monster_id"], ["catalog_monsters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["save_ability_score_id"],
            ["catalog_ability_score_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_monster_speeds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monster_id", sa.UUID(), nullable=False),
        sa.Column("walk", sa.String(length=50), nullable=True),
        sa.Column("burrow", sa.String(length=50), nullable=True),
        sa.Column("climb", sa.String(length=50), nullable=True),
        sa.Column("fly", sa.String(length=50), nullable=True),
        sa.Column("swim", sa.String(length=50), nullable=True),
        sa.Column("hover", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monster_id"], ["catalog_monsters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("monster_id"),
    )
    op.create_table(
        "catalog_monsters_i18n",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["catalog_monsters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "locale", name="uq_catalog_monsters_i18n"),
    )
    op.create_table(
        "catalog_monster_action_damages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column("damage_dice", sa.String(length=20), nullable=False),
        sa.Column("damage_type_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"], ["catalog_monster_actions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["damage_type_id"],
            ["catalog_damage_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_monster_legendary_action_damages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column("damage_dice", sa.String(length=20), nullable=False),
        sa.Column("damage_type_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"], ["catalog_monster_legendary_actions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["damage_type_id"],
            ["catalog_damage_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_monster_reaction_damages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column("damage_dice", sa.String(length=20), nullable=False),
        sa.Column("damage_type_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"], ["catalog_monster_reactions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["damage_type_id"],
            ["catalog_damage_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_monster_special_ability_damages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column("damage_dice", sa.String(length=20), nullable=False),
        sa.Column("damage_type_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"], ["catalog_monster_special_abilities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["damage_type_id"],
            ["catalog_damage_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "catalog_monster_proficiencies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monster_id", sa.UUID(), nullable=False),
        sa.Column("proficiency_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monster_id"], ["catalog_monsters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["proficiency_id"], ["catalog_proficiencies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("catalog_monster_proficiencies")
    op.drop_table("catalog_monster_special_ability_damages")
    op.drop_table("catalog_monster_reaction_damages")
    op.drop_table("catalog_monster_legendary_action_damages")
    op.drop_table("catalog_monster_action_damages")
    op.drop_table("catalog_monsters_i18n")
    op.drop_table("catalog_monster_speeds")
    op.drop_table("catalog_monster_special_abilities")
    op.drop_table("catalog_monster_senses")
    op.drop_table("catalog_monster_reactions")
    op.drop_table("catalog_monster_legendary_actions")
    op.drop_table("catalog_monster_damage_modifiers")
    op.drop_table("catalog_monster_condition_immunities")
    op.drop_table("catalog_monster_armor_classes")
    op.drop_table("catalog_monster_actions")
    op.drop_index(op.f("ix_catalog_monsters_index"), table_name="catalog_monsters")
    op.drop_table("catalog_monsters")
    # ### end Alembic commands ###
    sa.Enum(name="damagemodifiertype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="creaturesize").drop(op.get_bind(), checkfirst=True)
